#!/usr/bin/env bash
# gen-index.sh — INDEX.md is DERIVED from the head block of every entries/<id>.md
# (the ```entry fence: status · hook · anchors · landing), one row per entry,
# grouped open · adopted · closed and alphabetical within a group. The entry is
# the one home of every machine-read fact about a mechanism; this file has no
# facts of its own, so a landing touches one file and regenerates
# (learning-loop-home-is-prose). `97-iterlog` reds a stale INDEX. Narrative —
# harvest notes, owner rulings, the harvest-completion ledger — lives in NOTES.md.
#   gen-index.sh            rewrite <this dir>/INDEX.md
#   gen-index.sh --stdout   print instead (what the check diffs against)
#   gen-index.sh [--stdout] <root>   another iteration-log root (fixtures)
set -uo pipefail
export LC_ALL=C
D=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
to_stdout=0; root=$D
for a in "$@"; do case "$a" in --stdout) to_stdout=1 ;; *) root=$a ;; esac; done
[ -d "$root/entries" ] || { echo "gen-index: no entries/ under $root" >&2; exit 2; }

# The status groups render() emits, and the ONLY list any count of its output
# may be taken over. Kept as one name because the summary line below used to
# count with '^| [a-z]', which also matches the table HEADER (its id column is
# literally 'id') — the generator over-reported its own output by exactly one
# row, and that one row masked the case worth seeing: an entry whose status is
# outside the vocabulary renders NO row, and rows < entries is how you find it.
STATUSES='open adopted closed'

row_count() { # INDEX file -> DATA rows, counted over the same list render groups on
  local alt=${STATUSES// /|}
  command grep -cE "^\| [^|]+ \| ($alt) \|" "$1"
}

entry_row() { # file status-wanted -> one table row when the entry has that status
  awk -v want="$2" -v id="$(basename "$1" .md)" '
    /^```entry[[:space:]]*$/ { inb=1; next }
    inb && /^```/ { inb=0; exit }
    inb { k=$0; sub(/:.*/, "", k); v=$0; sub(/^[a-z_]+:[[:space:]]*/, "", v); F[k]=v }
    END {
      if (F["status"] != want) exit
      for (k in F) gsub(/\|/, "\\|", F[k])     # a bare pipe splits the row for every renderer and parser
      printf "| %s | %s | %s | %s | %s |\n", id, F["status"], F["hook"], F["anchors"], F["landing"]
    }' "$1"
}

render() {
  cat <<'EOF'
# delivery-workflow — iteration log (durable learning home)

> GENERATED by `iteration-log/gen-index.sh` from the head block of every
> `entries/<id>.md` — never edit this file: edit the entry and regenerate
> (`97-iterlog` reds a stale INDEX). One row per mechanism entry, grouped
> open · adopted · closed, alphabetical within a group; every id is
> `entries/<id>.md`, and a closed entry keeps its file (git history is not a
> home). The harvest notes, owner rulings and the `harvest-completion:` ledger
> are narrative and live in `NOTES.md`. Promotion judgment and the two-anchor
> bar: `runtime-docs/review-standards.md` §14.
>
> Columns: `id · status · hook · anchors (topic: observation t= stamps) ·
> landing (commit · notes)`. An adopted row cites the mechanism's landing
> commit; a closed row cites its closing evidence.

| id | status | hook | anchors (t=) | landing |
|---|---|---|---|---|
EOF
  local st f
  for st in $STATUSES; do
    for f in "$root"/entries/*.md; do
      [ -f "$f" ] || continue
      entry_row "$f" "$st"
    done
  done
}

if [ "$to_stdout" -eq 1 ]; then
  render
else
  tmp=$(mktemp "$root/.INDEX.XXXXXX") || exit 3
  render > "$tmp" && mv "$tmp" "$root/INDEX.md" \
    && echo "INDEX.md regenerated: $(row_count "$root/INDEX.md") rows from $(find "$root/entries" -name '*.md' -type f | wc -l | tr -d ' ') entries"
fi
